# Generated by Django 3.1.7 on 2021-04-11 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('system_type', models.CharField(choices=[('ED', 'School'), ('PG', 'Power Generation'), ('TF', 'Some other Facility'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('system_no', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coid', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SitePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=125)),
                ('status', models.CharField(choices=[('AB', 'Abandoned'), ('AC', 'Active Compliant'), ('DS', 'Destroyed'), ('IA', 'Inactive'), ('SB', 'Stand By waiting acitvation'), ('MO', 'Monitoring')], default='SB', max_length=2)),
                ('sys_site_n', models.CharField(max_length=15, unique=True)),
                ('system_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.agency', to_field='system_no')),
            ],
        ),
    ]
